### ISSUE TITLE
Node 4.1.1 and sqllite3 issue??

### ISSUE THREAD

**Issue by oneezy** [switchbitio/ghost-theme-with-gulp#1]
I believe this is a problem with the new Node release (4.0).. But it's not allowing me to install Ghost from the initial "npm install" command. Everything else seems to install in the `node_modules` folder however.

I think this is the fix for this, but I'm still testing: [Node 4.0 w/ Ghost](https://asciinema.org/a/26668)

**Below is my output:**

```
Oneeezy@Oneeezy-PC MINGW64 ~/desktop/www/ghost-gulp
$ npm install
npm WARN package.json my-ghost-theme@1.0.0 No repository field.
npm WARN package.json my-ghost-theme@1.0.0 No license field.
npm WARN engine ghost@0.7.1: wanted: {"node":"~0.10.0 || ~0.12.0","iojs":"~1.2.0"} (current: {"node":"                     4.1.1","npm":"2.14.4"})
npm WARN engine html-to-text@1.3.0: wanted: {"node":">= 0.8.0 <=0.12 || <=1.4.0"} (current: {"node":"4                     .1.1","npm":"2.14.4"})

> sqlite3@3.0.8 install C:\Users\Oneeezy\desktop\www\ghost-gulp\node_modules\ghost\node_modules\sqlite                     3
> node-pre-gyp install --fallback-to-build


C:\Users\Oneeezy\desktop\www\ghost-gulp\node_modules\ghost\node_modules\sqlite3>if not defined npm_con                     fig_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node                     -gyp\bin\node-gyp.js" clean )  else (node  clean )

C:\Users\Oneeezy\desktop\www\ghost-gulp\node_modules\ghost\node_modules\sqlite3>if not defined npm_con                     fig_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node                     -gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\Oneeezy\desktop\www\ghost-gulp\n                     ode_modules\ghost\node_modules\sqlite3\lib\binding\node-v46-win32-x64\node_sqlite3.node --module_name=                     node_sqlite3 --module_path=C:\Users\Oneeezy\desktop\www\ghost-gulp\node_modules\ghost\node_modules\sql                     ite3\lib\binding\node-v46-win32-x64 )  else (node  configure --fallback-to-build --module=C:\Users\One                     eezy\desktop\www\ghost-gulp\node_modules\ghost\node_modules\sqlite3\lib\binding\node-v46-win32-x64\nod                     e_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Oneeezy\desktop\www\ghost-gulp\node_m                     odules\ghost\node_modules\sqlite3\lib\binding\node-v46-win32-x64 )

C:\Users\Oneeezy\desktop\www\ghost-gulp\node_modules\ghost\node_modules\sqlite3>if not defined npm_con                     fig_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node                     -gyp\bin\node-gyp.js" build --fallback-to-build --module=C:\Users\Oneeezy\desktop\www\ghost-gulp\node_                     modules\ghost\node_modules\sqlite3\lib\binding\node-v46-win32-x64\node_sqlite3.node --module_name=node                     _sqlite3 --module_path=C:\Users\Oneeezy\desktop\www\ghost-gulp\node_modules\ghost\node_modules\sqlite3                     \lib\binding\node-v46-win32-x64 )  else (node  build --fallback-to-build --module=C:\Users\Oneeezy\des                     ktop\www\ghost-gulp\node_modules\ghost\node_modules\sqlite3\lib\binding\node-v46-win32-x64\node_sqlite                     3.node --module_name=node_sqlite3 --module_path=C:\Users\Oneeezy\desktop\www\ghost-gulp\node_modules\g                     host\node_modules\sqlite3\lib\binding\node-v46-win32-x64 )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" sw                     itch.
  unpack_sqlite_dep
  'python' is not recognized as an internal or external command,
  operable program or batch file.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets(172,5): error MSB60                     06: "cmd.exe" exited with code 1. [C:\Users\Oneeezy\desktop\www\ghost-gulp\node_modules\ghost\node_mod                     ules\sqlite3\build\deps\action_before_build.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit cod                     e: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-                     gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\                     node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\Oneeezy\\                     desktop\\www\\ghost-gulp\\node_modules\\ghost\\node_modules\\sqlite3\\lib\\binding\\node-v46-win32-x64                     \\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Users\\Oneeezy\\desktop\\www\\gho                     st-gulp\\node_modules\\ghost\\node_modules\\sqlite3\\lib\\binding\\node-v46-win32-x64"
gyp ERR! cwd C:\Users\Oneeezy\desktop\www\ghost-gulp\node_modules\ghost\node_modules\sqlite3
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\U                     sers\Oneeezy\desktop\www\ghost-gulp\node_modules\ghost\node_modules\sqlite3\lib\binding\node-v46-win32                     -x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\Oneeezy\desktop\www\ghost-gul                     p\node_modules\ghost\node_modules\sqlite3\lib\binding\node-v46-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Oneeezy\Desktop\www\ghost-gulp\node_                     modules\ghost\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:817:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Oneeezy\\Desktop\\www\\gho                     st-gulp\\node_modules\\ghost\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "i                     nstall" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Oneeezy\desktop\www\ghost-gulp\node_modules\ghost\node_modules\sqlite3
node-pre-gyp ERR! node -v v4.1.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\Oneeezy\desktop\www\ghost-                     gulp\node_modules\ghost\node_modules\sqlite3\lib\binding\node-v46-win32-x64\node_sqlite3.node --module                     _name=node_sqlite3 --module_path=C:\Users\Oneeezy\desktop\www\ghost-gulp\node_modules\ghost\node_modul                     es\sqlite3\lib\binding\node-v46-win32-x64' (1)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin                     \\npm-cli.js" "install"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.0.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.0.8 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Oneeezy\desktop\www\ghost-gulp\npm-debug.log

Oneeezy@Oneeezy-PC MINGW64 ~/desktop/www/ghost-gulp
$ node -v
v4.1.1

Oneeezy@Oneeezy-PC MINGW64 ~/desktop/www/ghost-gulp
$ npm -v
2.14.4
```

**Comment by donovanmuller** [comment]
Sorry for the **very** late reply...

I have updated Ghost and all works with Node 4 LTS release.
[Updated the posts](http://blog.switchbit.io/developing-a-ghost-theme-with-gulp-part-2/#update20160128) to include the hint to use the correct Node version.

Hope this resolves your issue?
